### ISSUE TITLE
An Issue!

### ISSUE THREAD

**Issue by MehdiRaash** [EthanRBrown/learning-javascript-3e#1]
hello, I know this place is not for these questions but it was somehow urgent for me!
I download this book from it-ebooks.info, the questions is should I buy it?
Isn't this book like You-Dont-Know-JS series open-source?

**Comment by EthanRBrown** [comment]
This book is not open source, and certainly _I_ think you should buy it!  What you shouldn't do is steal it, which is what you're doing if you download it from an illicit website.  If you buy the digital copy, it is DRM-free, so you may use it on whatever devices you wish.  But O'Reilly and I both deserve to make money on the significant effort that went into this book.

**Comment by MehdiRaash** [comment]
Dear author, I didn't intend to steal a book, There was a doubt for me, about specially this book so I decided to ask for clarification. Thank you for writing this book.

**Comment by EthanRBrown** [comment]
You're welcome, I hope you enjoy it!
